version: "3.8"

services:

  backend:
    depends_on:
      - db
    build: ./server
    ports:
      - 3001:3001
    environment:
      DB_URL: postgres://db/server
    volumes:
      - ./server:/app

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=nick
      - POSTGRES_PASSWORD=hawaiian5
      - POSTGRES_DB=products
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/db

volumes:
  db-data: null
